import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { type Scene, parseScene } from '@tyto/core';
import { exportHtml } from '@tyto/export-html';
import { bundledFont } from '@tyto/fonts';
import pixelmatch from 'pixelmatch';
import { PNG } from 'pngjs';
import { type ElectronApplication, _electron } from 'playwright';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import { type CaptureWindow, createDebuggerRasterizer } from '../src/main/rasterizer.js';

/**
 * **E5.4's acceptance criterion, which had no home until this file.** TYTO-133.
 *
 * The desktop adapter has to produce the same bytes as the Playwright one within the visual
 * tolerance, and `packages/raster` cannot ask that question — it runs no Electron. So the
 * question is asked here, against the references `raster.visual.test.ts` already recorded and
 * committed, rather than against a second set recorded from the thing under test. A
 * reference generated by the adapter it is meant to check is not a reference.
 *
 * **What runs where, and it is the whole design of this file.** The adapter itself runs in
 * *this* process — the real `createDebuggerRasterizer`, imported from `src/main`, not a copy
 * of its logic. Only the window operations cross into Electron, through the `CaptureWindow`
 * seam the adapter declares for exactly this. So what is under test is the shipped code path
 * and not a reimplementation of it, which is the failure mode
 * `offscreen-raster.desktop.test.ts` was careful to be honest about: that suite measured a
 * mechanism, this one measures the adapter.
 *
 * **Shapes are compared against Playwright's reference and glyphs are not, and the reason is
 * a number.** The two adapters drive different Chromium builds — measured in this card,
 * `electron=152.0.7977.78 playwright=153.0.8010.12` — and a font rasterizer changes between
 * builds while a rectangle does not. Against Playwright's references, as the app actually
 * launches:
 *
 * ```
 *               win32     linux (ubuntu-latest)
 * shapes.feed   0.0656%   0.0000%   within the 0.1% tolerance on both
 * alpha.square  0.0000%   0.0000%   identical on both
 * text.feed     1.2219%   0.9587%   ten times the tolerance on both
 * ```
 *
 * So `shapes.feed` and `alpha.square` carry E5.4's acceptance criterion — *the same fixtures
 * within the visual tolerance of the Playwright references* — and they carry it on every
 * platform, because neither is keyed on one. `text.feed` is compared against a reference
 * recorded by **this** adapter instead, in `e2e/__fixtures__/reference/`, and that is a
 * regression check rather than a parity check. Saying so is the point: widening the tolerance
 * to 1.3% so that one number could be called parity would have made the other two stop
 * meaning anything. ADR 0028.
 *
 * **The launch carries no `DETERMINISM_ARGS`, deliberately.** ADR 0028 decided the shipped app
 * does not apply them, so a suite that passed them would be measuring a configuration nobody
 * ships — the exact instrument failure this repository keeps recording. The numbers above are
 * the app as it runs.
 */

const here = dirname(fileURLToPath(import.meta.url));

/**
 * `packages/raster`'s fixtures, by walking the repository rather than by resolving the
 * package.
 *
 * `@tyto/raster` exports its `dist`, and these files are in `src` — deliberately, since a
 * reference PNG is test data and not something the package ships. A relative walk is the
 * honest way to say "the other package's test data", and it breaks loudly (the `existsSync`
 * below) rather than silently comparing against nothing if the layout ever moves.
 */
const RASTER_FIXTURES = join(here, '..', '..', '..', 'packages', 'raster', 'src', '__fixtures__');
const REFERENCE_DIR = join(RASTER_FIXTURES, 'reference');

/** This adapter's own references, for the fixture Playwright's cannot answer for. */
const DESKTOP_REFERENCE_DIR = join(here, '__fixtures__', 'reference');
const DIFF_DIR = join(here, '__diff__');

/** `UPDATE_DESKTOP_RASTER_REFERENCE=1 pnpm --filter @tyto/desktop test:desktop` records. */
const UPDATING = process.env['UPDATE_DESKTOP_RASTER_REFERENCE'] === '1';

/** The same 0.001 `raster.visual.test.ts` defends, and for the same reasons. */
const TOLERANCE = 0.001;
const THRESHOLD = 0.1;

const PLATFORM = process.platform;

let app: ElectronApplication;

/**
 * The checkerboard `shapes.json` points its image at.
 *
 * Copied from `raster.visual.test.ts` rather than imported, because it is that suite's
 * private helper and exporting it would make a test fixture part of a package's surface. The
 * bytes have to be identical for the comparison to mean anything, which is what the
 * reference PNG itself enforces: change one of the two and the fraction goes past tolerance
 * and this suite says so.
 */
function checkerboardDataUri(): string {
  const size = 64;
  const cell = 8;
  const png = new PNG({ width: size, height: size });

  for (let y = 0; y < size; y += 1) {
    for (let x = 0; x < size; x += 1) {
      const dark = (Math.floor(x / cell) + Math.floor(y / cell)) % 2 === 0;
      const index = (y * size + x) * 4;
      png.data[index] = dark ? 30 : 235;
      png.data[index + 1] = dark ? 40 : 120;
      png.data[index + 2] = dark ? 90 : 30;
      png.data[index + 3] = 255;
    }
  }

  return `data:image/png;base64,${PNG.sync.write(png).toString('base64')}`;
}

const CHECKERBOARD = checkerboardDataUri();

interface Document {
  readonly name: string;
  readonly html: string;
  readonly width: number;
  readonly height: number;
  readonly perPlatform: boolean;
}

function sceneOf(fixture: unknown): Scene {
  const parsed = parseScene(fixture);
  if (!parsed.ok) throw new Error(parsed.error.map((item) => item.message).join('; '));
  return parsed.value;
}

function documentsOf(file: string, perPlatform = false): readonly Document[] {
  const fixture: unknown = JSON.parse(readFileSync(join(RASTER_FIXTURES, file), 'utf8'));
  const exported = exportHtml(sceneOf(fixture), {
    resources: { asset: () => CHECKERBOARD, font: bundledFont },
  });

  if (!exported.ok) throw new Error(exported.error.map((item) => item.message).join('; '));

  return exported.value.map((frame) => ({
    name: `${frame.artwork.id}.${frame.frame.format}`,
    html: frame.html,
    width: frame.frame.size.w,
    height: frame.frame.size.h,
    perPlatform,
  }));
}

function referenceFile(document: Document): string {
  return document.perPlatform ? `${document.name}.${PLATFORM}.png` : `${document.name}.png`;
}

/**
 * A window in the Electron this suite launched, driven from here.
 *
 * The handle is an integer because everything between the two processes is JSON — a
 * `BrowserWindow` cannot cross. The map lives on the main process's `globalThis` for the
 * lifetime of the launch; the adapter destroys each window it is handed, and `destroy`
 * drops the entry so a long suite does not accumulate them.
 */
async function remoteWindow(size: { width: number; height: number }): Promise<CaptureWindow> {
  const id = await app.evaluate(({ BrowserWindow }, wanted) => {
    const store = ((globalThis as Record<string, unknown>)['__tytoCaptureWindows'] ??= new Map<
      number,
      Electron.BrowserWindow
    >()) as Map<number, Electron.BrowserWindow>;

    const window = new BrowserWindow({
      show: false,
      width: wanted.width,
      height: wanted.height,
      useContentSize: true,
      frame: false,
      transparent: true,
      webPreferences: { contextIsolation: true, nodeIntegration: false, sandbox: true },
    });

    const handle = store.size + 1;
    store.set(handle, window);
    return handle;
  }, size);

  return {
    loadFile: async (file) => {
      await app.evaluate(
        async (_electronModule, arguments_) => {
          const store = (globalThis as Record<string, unknown>)['__tytoCaptureWindows'] as Map<
            number,
            Electron.BrowserWindow
          >;
          const window = store.get(arguments_.id);
          if (!window) throw new Error(`no such window: ${String(arguments_.id)}`);
          await window.loadFile(arguments_.file);
        },
        { id, file },
      );
    },
    executeJavaScript: async (code) =>
      app.evaluate(
        async (_electronModule, arguments_) => {
          const store = (globalThis as Record<string, unknown>)['__tytoCaptureWindows'] as Map<
            number,
            Electron.BrowserWindow
          >;
          const window = store.get(arguments_.id);
          if (!window) throw new Error(`no such window: ${String(arguments_.id)}`);
          return window.webContents.executeJavaScript(arguments_.code) as Promise<unknown>;
        },
        { id, code },
      ),
    attachDebugger: (protocolVersion) => {
      // Synchronous on the port because `webContents.debugger.attach` is synchronous. The
      // promise is awaited by the next `sendCommand`, which cannot run before it settles —
      // Electron's protocol queue is ordered, and both go through the same `app.evaluate`
      // channel, which is also ordered.
      void app.evaluate(
        (_electronModule, arguments_) => {
          const store = (globalThis as Record<string, unknown>)['__tytoCaptureWindows'] as Map<
            number,
            Electron.BrowserWindow
          >;
          const window = store.get(arguments_.id);
          if (!window) throw new Error(`no such window: ${String(arguments_.id)}`);
          window.webContents.debugger.attach(arguments_.protocolVersion);
        },
        { id, protocolVersion },
      );
    },
    sendCommand: async (method, parameters) =>
      app.evaluate(
        async (_electronModule, arguments_) => {
          const store = (globalThis as Record<string, unknown>)['__tytoCaptureWindows'] as Map<
            number,
            Electron.BrowserWindow
          >;
          const window = store.get(arguments_.id);
          if (!window) throw new Error(`no such window: ${String(arguments_.id)}`);
          return window.webContents.debugger.sendCommand(
            arguments_.method,
            arguments_.parameters,
          ) as Promise<unknown>;
        },
        { id, method, parameters: parameters ?? {} },
      ),
    detachDebugger: () => {
      void app.evaluate(
        (_electronModule, arguments_) => {
          const store = (globalThis as Record<string, unknown>)['__tytoCaptureWindows'] as Map<
            number,
            Electron.BrowserWindow
          >;
          store.get(arguments_.id)?.webContents.debugger.detach();
        },
        { id },
      );
    },
    destroy: () => {
      void app
        .evaluate(
          (_electronModule, arguments_) => {
            const store = (globalThis as Record<string, unknown>)['__tytoCaptureWindows'] as Map<
              number,
              Electron.BrowserWindow
            >;
            store.get(arguments_.id)?.destroy();
            store.delete(arguments_.id);
          },
          { id },
        )
        .catch(() => {
          // The launch is being torn down; a window that cannot be destroyed is already gone.
        });
    },
  };
}

const rasterizer = createDebuggerRasterizer({ createWindow: remoteWindow });

beforeAll(async () => {
  if (!existsSync(REFERENCE_DIR)) {
    throw new Error(
      `${REFERENCE_DIR} is missing — this suite compares against the references ` +
        '`packages/raster/src/raster.visual.test.ts` recorded, and cannot run without them.',
    );
  }

  app = await _electron.launch({
    // The same five flags the CLI's Chromium is launched with. They are what makes a
    // reference comparable at all; whether the *shipped* app applies them is a separate
    // question this card answers in `src/main/index.ts`.
    args: ['.'],
    cwd: join(here, '..'),
    env: { ...process.env, TYTO_HEADLESS: '1' },
  });
});

afterAll(async () => {
  await app?.close();
});

/**
 * The fraction of pixels that differ from the committed Playwright reference.
 *
 * A missing reference for *this* platform is not a failure for the per-platform fixture —
 * it is the honest state of a repository whose references are recorded one platform at a
 * time — but it is never silent: the caller prints what it skipped and why. A missing
 * reference for a platform-independent fixture *is* a failure, because there is nothing to
 * be missing.
 */
function mismatchFraction(document: Document, rendered: Uint8Array): number {
  const directory = document.perPlatform ? DESKTOP_REFERENCE_DIR : REFERENCE_DIR;
  const reference = PNG.sync.read(readFileSync(join(directory, referenceFile(document))));
  const actual = PNG.sync.read(Buffer.from(rendered));

  if (reference.width !== actual.width || reference.height !== actual.height) {
    throw new Error(
      `${document.name}: the adapter returned ${String(actual.width)}×${String(actual.height)} ` +
        `where the Playwright reference is ${String(reference.width)}×${String(reference.height)}. ` +
        'A size difference is not a tolerance question.',
    );
  }

  const diff = new PNG({ width: reference.width, height: reference.height });
  const differing = pixelmatch(
    reference.data,
    actual.data,
    diff.data,
    reference.width,
    reference.height,
    { threshold: THRESHOLD },
  );

  const fraction = differing / (reference.width * reference.height);
  if (fraction > TOLERANCE) {
    mkdirSync(DIFF_DIR, { recursive: true });
    writeFileSync(join(DIFF_DIR, `${document.name}.actual.png`), Buffer.from(rendered));
    writeFileSync(join(DIFF_DIR, `${document.name}.diff.png`), PNG.sync.write(diff));
  }

  return fraction;
}

async function render(document: Document): Promise<Uint8Array> {
  return rasterizer.raster(document.html, { width: document.width, height: document.height });
}

const PORTABLE = [...documentsOf('shapes.json'), ...documentsOf('alpha.json')];
const GLYPHS = documentsOf('text.json', true);

describe('the debugger-captured adapter against the Playwright references', () => {
  it.each(PORTABLE.map((document) => [document.name, document] as const))(
    '%s matches within tolerance',
    async (_name, document) => {
      const fraction = mismatchFraction(document, await render(document));

      process.stdout.write(
        `[TYTO-133] platform=${PLATFORM} ${document.name} mismatch=${(fraction * 100).toFixed(4)}%\n`,
      );
      expect(fraction).toBeLessThanOrEqual(TOLERANCE);
    },
    120_000,
  );

  it.each(GLYPHS.map((document) => [document.name, document] as const))(
    '%s matches within tolerance, where this platform has a reference',
    async (_name, document) => {
      const file = join(DESKTOP_REFERENCE_DIR, referenceFile(document));

      if (UPDATING) {
        mkdirSync(DESKTOP_REFERENCE_DIR, { recursive: true });
        writeFileSync(file, Buffer.from(await render(document)));
        process.stdout.write(`[TYTO-133] recorded ${referenceFile(document)}\n`);
        return;
      }

      if (!existsSync(file)) {
        // **Not a failure, and never silent.** A glyph reference can only be recorded on the
        // platform it is for, so a repository that has win32's and not linux's is in an
        // honest intermediate state rather than a broken one — failing here would paint every
        // later `apps/desktop` pull request red over a file nobody on this machine can
        // produce. A skipped comparison that printed nothing, on the other hand, reads
        // exactly like one that passed.
        // Written into `__diff__/` so the workflow's artifact carries it: recording a linux
        // reference from a Windows machine is impossible, and downloading this file from the
        // run is the only way one ever gets committed.
        mkdirSync(DIFF_DIR, { recursive: true });
        writeFileSync(join(DIFF_DIR, referenceFile(document)), Buffer.from(await render(document)));

        process.stdout.write(
          `[TYTO-133] platform=${PLATFORM} ${document.name} NOT COMPARED — no ` +
            `e2e/__fixtures__/reference/${referenceFile(document)}. Record it on ${PLATFORM} ` +
            'with UPDATE_DESKTOP_RASTER_REFERENCE=1, or take it from this run’s ' +
            'desktop-raster-diffs artifact, and commit it (Git LFS).\n',
        );
        return;
      }

      const fraction = mismatchFraction(document, await render(document));

      process.stdout.write(
        `[TYTO-133] platform=${PLATFORM} ${document.name} mismatch=${(fraction * 100).toFixed(4)}%\n`,
      );
      expect(fraction).toBeLessThanOrEqual(TOLERANCE);
    },
    120_000,
  );

  it('returns every format the port promises, checked in the bytes', async () => {
    const document = PORTABLE[0];
    if (!document) throw new Error('no portable fixture');

    const png = await rasterizer.raster(document.html, { width: 200, height: 200 });
    const jpeg = await rasterizer.raster(document.html, {
      width: 200,
      height: 200,
      format: 'jpeg',
      quality: 80,
    });
    const webp = await rasterizer.raster(document.html, {
      width: 200,
      height: 200,
      format: 'webp',
      quality: 80,
    });

    const magic = (bytes: Uint8Array, from: number, length: number): string =>
      Buffer.from(bytes)
        .subarray(from, from + length)
        .toString('hex');

    // ADR 0027 closed the `webp` question by measuring the container rather than trusting
    // the call. The same assertion, on the adapter rather than on a probe.
    expect(magic(png, 0, 4)).toBe('89504e47');
    expect(magic(jpeg, 0, 3)).toBe('ffd8ff');
    expect(`${magic(webp, 0, 4)}/${magic(webp, 8, 4)}`).toBe('52494646/57454250');
  }, 120_000);

  it('gives scale to the pixels and not to the layout', async () => {
    const document = PORTABLE[0];
    if (!document) throw new Error('no portable fixture');

    const once = PNG.sync.read(
      Buffer.from(await rasterizer.raster(document.html, { width: 300, height: 300 })),
    );
    const twice = PNG.sync.read(
      Buffer.from(await rasterizer.raster(document.html, { width: 300, height: 300, scale: 2 })),
    );

    // 600, not 1200: `clip.scale` stays 1 so the two do not multiply (ADR 0027).
    expect([once.width, once.height]).toEqual([300, 300]);
    expect([twice.width, twice.height]).toEqual([600, 600]);
  }, 120_000);
});
