import {
  type DiagnosticCode,
  diagnosticCodeDefinition,
  diagnosticCodeList,
  placeholderNames,
} from '@tyto/core';

import { type DesktopCode, desktopCodes } from './desktop-codes.ts';

/**
 * Renders the diagnostic catalog as Markdown.
 *
 * Pure so it can be tested without touching disk, and separate from the writer so the
 * same string is what the test compares against the committed file.
 */

export const GENERATED_HEADER =
  '<!-- Generated by `pnpm docs:gen` from packages/core/src/diagnostics/codes.ts and ' +
  'tools/docs-gen/src/desktop-codes.ts. Do not edit. -->';

/** A pipe inside a summary would end the Markdown table cell early. */
const escapeCell = (text: string) => text.replaceAll('|', String.raw`\|`);

const yesNo = (fatal: boolean) => (fatal ? 'yes' : 'no');

function renderCode(code: DiagnosticCode): string {
  const definition = diagnosticCodeDefinition(code);
  const parameters = placeholderNames(definition.template);

  return [
    `### \`${code}\``,
    '',
    `**Severity:** ${definition.severity} · **Fatal:** ${yesNo(definition.fatal)} · ` +
      `**Spec:** \`${definition.spec}\``,
    '',
    definition.summary,
    '',
    definition.fatality,
    '',
    '```',
    definition.template,
    '```',
    '',
    parameters.length > 0
      ? `Parameters: ${parameters.map((name) => `\`${name}\``).join(', ')}`
      : 'Parameters: none',
  ].join('\n');
}

/**
 * The section for codes the window mints (TYTO-141). Separate from the catalogue above because
 * these have no template, no spec and no fatality: they are the window saying something about
 * the app, not a stage saying something about a brief.
 */
function desktopSection(): string[] {
  const renderDesktopCode = (entry: DesktopCode) =>
    [
      `### \`${entry.code}\``,
      '',
      `**Severity:** ${entry.severity} · **Minted in:** \`apps/desktop/src/${entry.mintedIn}\``,
      '',
      entry.summary,
      '',
      `Message: the \`${entry.messageKey}\` sentence in the window's language ` +
        `("${entry.english}" in English), then ${entry.suffix}.`,
    ].join('\n');

  return [
    '## Codes the desktop window mints',
    '',
    'These are **not compiler diagnostics** and have no entry in',
    '`packages/core/src/diagnostics/codes.ts`. The desktop window builds them itself and puts',
    'them in the problems panel, where they are drawn exactly like the codes above — so they',
    'are listed here for whoever greps a code off a screenshot.',
    '',
    '**Who mints them, and why:** the renderer, because the renderer owns the locale and main',
    'does not. Main can tell that a file moved or that a folder held no templates; only the',
    'window knows which language to say it in. No brief can cause one, and the CLI never',
    'reports one. `tools/repo-checks` fails when a code literal under `apps/desktop` is',
    'missing from this document.',
    '',
    ...desktopCodes.map(renderDesktopCode).flatMap((section) => [section, '']),
  ];
}

export function renderDiagnosticCodes(): string {
  const errors = diagnosticCodeList.filter((code) => code.startsWith('E_'));
  const warnings = diagnosticCodeList.filter((code) => code.startsWith('W_'));

  const summaryTable = [
    '| Code | Severity | Fatal | Summary |',
    '| --- | --- | --- | --- |',
    ...diagnosticCodeList.map((code) => {
      const definition = diagnosticCodeDefinition(code);
      return (
        `| \`${code}\` | ${definition.severity} | ${yesNo(definition.fatal)} | ` +
        `${escapeCell(definition.summary)} |`
      );
    }),
  ].join('\n');

  const fatalTable = [
    '| Code | Fatal | Why |',
    '| --- | --- | --- |',
    ...errors.map((code) => {
      const definition = diagnosticCodeDefinition(code);
      return `| \`${code}\` | ${yesNo(definition.fatal)} | ${escapeCell(definition.fatality)} |`;
    }),
  ].join('\n');

  return [
    GENERATED_HEADER,
    '',
    '# Diagnostic codes',
    '',
    'Every error and warning a compiler stage can report, and — in the last section — the',
    'few the desktop window mints itself. A stage names a code and supplies its',
    'parameters; the message is rendered from the template below, so a code and its',
    'wording cannot drift apart.',
    '',
    'Two properties, and they are not the same question (ADR 0025). **Severity** says how',
    'bad it is for the author: an error fails a build and a warning does not, wherever the',
    'diagnostic ended up. **Fatality** says whether the stage that met it could still hand',
    'back a value. A warning has ridden the ok branch since ADR 0013; since ADR 0025 a',
    'non-fatal *error* rides there too, beside the part of the value it did not cost — so a',
    'brief with one unreadable directive renders the other nineteen slots, and still exits',
    'non-zero.',
    '',
    summaryTable,
    '',
    '## What is fatal, and why',
    '',
    'Fatal means **nothing can be drawn**, not "serious". The test is whether a frame could',
    'exist without the thing that is missing. A warning is never fatal, so only the errors',
    'are listed here.',
    '',
    'Three entries were fatal for a reason that was a deadline rather than a principle,',
    'and ADR 0035 is the thing they were waiting for. `E_MISSING_REQUIRED_SLOT`,',
    '`E_EXPORT_ASSET_UNRESOLVED` and `E_EXPORT_UNSUPPORTED` each left a hole in the artwork',
    'that nothing in the artwork named; the rule ADR 0025 set for them was "non-fatal only',
    'if the gap is visible", and the gap is now drawn — a stamp on every frame of an',
    'incomplete brief, and a crossed box where a picture the exporter could not load goes.',
    '',
    fatalTable,
    '',
    '## Errors',
    '',
    ...errors.map(renderCode).flatMap((section) => [section, '']),
    '## Warnings',
    '',
    ...warnings.map(renderCode).flatMap((section) => [section, '']),
    ...desktopSection(),
  ]
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trimEnd()
    .concat('\n');
}
