import {
  type DiagnosticCode,
  diagnosticCodeDefinition,
  diagnosticCodeList,
  placeholderNames,
} from '@tyto/core';

/**
 * Renders the diagnostic catalog as Markdown.
 *
 * Pure so it can be tested without touching disk, and separate from the writer so the
 * same string is what the test compares against the committed file.
 */

export const GENERATED_HEADER =
  '<!-- Generated by `pnpm docs:gen` from packages/core/src/diagnostics/codes.ts. Do not edit. -->';

/** A pipe inside a summary would end the Markdown table cell early. */
const escapeCell = (text: string) => text.replaceAll('|', String.raw`\|`);

function renderCode(code: DiagnosticCode): string {
  const definition = diagnosticCodeDefinition(code);
  const parameters = placeholderNames(definition.template);

  return [
    `### \`${code}\``,
    '',
    `**Severity:** ${definition.severity} · **Spec:** \`${definition.spec}\``,
    '',
    definition.summary,
    '',
    '```',
    definition.template,
    '```',
    '',
    parameters.length > 0
      ? `Parameters: ${parameters.map((name) => `\`${name}\``).join(', ')}`
      : 'Parameters: none',
  ].join('\n');
}

export function renderDiagnosticCodes(): string {
  const errors = diagnosticCodeList.filter((code) => code.startsWith('E_'));
  const warnings = diagnosticCodeList.filter((code) => code.startsWith('W_'));

  const summaryTable = [
    '| Code | Severity | Summary |',
    '| --- | --- | --- |',
    ...diagnosticCodeList.map((code) => {
      const definition = diagnosticCodeDefinition(code);
      return `| \`${code}\` | ${definition.severity} | ${escapeCell(definition.summary)} |`;
    }),
  ].join('\n');

  return [
    GENERATED_HEADER,
    '',
    '# Diagnostic codes',
    '',
    'Every error and warning Tyto can report. A stage names a code and supplies its',
    'parameters; the message is rendered from the template below, so a code and its',
    'wording cannot drift apart. Errors fail their stage; warnings ride along with a',
    'successful result (ADR 0013).',
    '',
    summaryTable,
    '',
    '## Errors',
    '',
    ...errors.map(renderCode).flatMap((section) => [section, '']),
    '## Warnings',
    '',
    ...warnings.map(renderCode).flatMap((section) => [section, '']),
  ]
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trimEnd()
    .concat('\n');
}
