import type { LRParser } from '@lezer/lr';

/**
 * Generated by `lezer-generator` from `brief.grammar` — `pnpm generate` rebuilds it, and
 * it is not committed. This declaration is the hand-written half: the generator emits
 * JavaScript and no types, and the shape it emits is one exported parser.
 */
export declare const parser: LRParser;
